### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by jperon** [berhalak/my-widgets#1]
Hi @berhalak,

Your `fiddle` widget is awesome. Under which license would you put it? Is it OK to use and adapt it in one’s project?

**Comment by berhalak** [comment]
Added licence. This fiddle widget will eventually land in `gristlabs/grist-widget` repository, so the licence should be the same.
And yes, you can do whatever you want with it :), glad it is useful for you.

**Comment by jperon** [comment]
Thank you very much, for this and for all your work on Grist!
